var_dict = list('cap.shape'=list( 'b'='bell','c'='conical','x'='convex','f'='flat', 'k'='knobbed','s'='sunken'),
'cap.surface'=list( 'f'='fibrous','g'='grooves','y'='scaly','s'='smooth'),
'cap.color'=list( 'n'='brown','b'='buff','c'='cinnamon','g'='gray','r'='green','p'='pink','u'='purple','e'='red','w'='white','y'='yellow'),
'bruises'=list( 't'='bruises','f'='no'),
'odor'=list( 'a'='almond','l'='anise','c'='creosote','y'='fishy','f'='foul','m'='musty','n'='none','p'='pungent','s'='spicy'),
'gill.attachment'=list( 'a'='attached','d'='descending','f'='free','n'='notched'),
'gill.spacing'=list( 'c'='close','w'='crowded','d'='distant'),
'gill.size'=list( 'b'='broad','n'='narrow'),
'gill.color'=list( 'k'='black','n'='brown','b'='buff','h'='chocolate','g'='gray', 'r'='green','o'='orange','p'='pink','u'='purple','e'='red','w'='white','y'='yellow'),
'stalk.shape'=list( 'e'='enlarging','t'='tapering'),
'stalk.root'=list( 'b'='bulbous','c'='club','u'='cup','e'='equal','z'='rhizomorphs','r'='rooted',missing='?'),
'stalk.surface.above.ring'=list( 'f'='fibrous','y'='scaly','k'='silky','s'='smooth'),
'stalk.surface.below.ring'=list( 'f'='fibrous','y'='scaly','k'='silky','s'='smooth'),
'stalk.color.above.ring'=list( 'n'='brown','b'='buff','c'='cinnamon','g'='gray','o'='orange','p'='pink','e'='red','w'='white','y'='yellow'),
'stalk.color.below.ring'=list( 'n'='brown','b'='buff','c'='cinnamon','g'='gray','o'='orange','p'='pink','e'='red','w'='white','y'='yellow'),
'veil.type'=list( 'p'='partial','u'='universal'),
'veil.color'=list( 'n'='brown','o'='orange','w'='white','y'='yellow'),
'ring.number'=list( 'n'='none','o'='one','t'='two'),
'ring.type'=list( 'c'='cobwebby','e'='evanescent','f'='flaring','l'='large','n'='none','p'='pendant','s'='sheathing','z'='zone'),
'spore.print.color'=list( 'k'='black','n'='brown','b'='buff','h'='chocolate','r'='green','o'='orange','u'='purple','w'='white','y'='yellow'),
'population'=list( 'a'='abundant','c'='clustered','n'='numerous','s'='scattered','v'='several','y'='solitary'),
'habitat'=list( 'g'='grasses','l'='leaves','m'='meadows','p'='paths','u'='urban','w'='waste','d'='woods')
)